export const ACTIONS = {
  HYDRATE_STORED_STATE: "hydrate-stored-state",
  ADD_INTRODUCTION: "add-introduction",
  SELECT_RENDER_MODE: "select-render-mode",
  ADD_SKILL: "add-skill",
  REMOVE_SKILL: "remove-skill",
  ADD_SOCIAL_PROFILE: "add-social-profile",
  ADD_ALTERNATIVE_SOCIAL_PROFILE: "add-alternative-social-profile",
  TOGGLE_BADGE: "toggle-badge",
  TOGGLE_GITHUB_STATS: "toggle-github-stats",
  STYLE_BADGES: "style-badges",
  TOGGLE_STYLE_COLOR: "toggle-style-color",
  ADD_REPO: "add-repo",
  DELETE_REPO: "delete-repo",
  ADD_SUPPORT: "add-support",
  TOGGLE_COPY_MODAL: "toggle-copy-modal",
  TOGGLE_ELEMENT: "toggle-element",
  CLOSE_ELEMENT: "close-element",
};
