export const SOCIAL_PLATFORMS = {
  behance: "",
  codepen: "",
  codesandbox: "",
  devdotto: "",
  discord: "",
  dribbble: "",
  facebook: "",
  github: "",
  gitlab: "",
  hashnode: "",
  instagram: "",
  linkedin: "",
  polywork: "",
  medium: "",
  rss: "",
  stackoverflow: "",
  twitter: "",
  youtube: "",
};
